#version 450
#extension GL_ARB_separate_shader_objects : enable

layout (local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0) buffer inbuf {
	float inData[ ];
};

layout(binding = 1) buffer outbuf {
	float outData[ ];
};

layout (constant_id = 0) const uint BUFFER_ELEMENTS = 2;		// This example only processes 2 floats.

void main() {
	uint index = gl_GlobalInvocationID.x;
	if (index >= BUFFER_ELEMENTS) 
		return;	
	outData[index] = inData[index] + 7 + 0.5;
}